# Generated by Django 4.2.4 on 2023-08-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
