# Generated by Django 4.2.4 on 2023-08-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_Otp',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
