# Generated by Django 4.2.4 on 2023-08-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0003_user_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Otp_Status',
            field=models.TextField(default='pending', max_length=20),
        ),
    ]
