# Generated by Django 4.2.4 on 2023-08-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0005_reviews_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
