# Generated by Django 4.2.4 on 2023-08-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0007_reviews_sentement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='Sentement',
        ),
        migrations.AddField(
            model_name='reviews',
            name='Sentiment',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
