# Generated by Django 4.2.4 on 2023-08-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0009_user_review_catgeory'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='Status',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
