# Generated by Django 4.2.4 on 2023-08-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0011_reviews_user_foreign'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Ratings',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Reviews',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
